overrides:
  typescript: 5.9.3

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd
